[project]
name = "cs"
version = "0.0.0"
description = "Companion materials for the Computational Statistics project."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Thomas Schmelzer" }]
license = { file = "LICENSE" }
dependencies = [
    "marimo>=0.18.4",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]

[dependency-groups]
dev = [
    "marimo==0.19.6",
]

[project.urls]
Homepage = "https://tschm.github.io/cs"
