[project]
name = "cs"
version = "0.0.0"
description = "Companion materials for the Computational Statistics project."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Thomas Schmelzer" }]
license = { file = "LICENSE" }
dependencies = [
    "cvxsimulator>=1.4.5",
    "marimo>=0.18.4",
    "numpy>=2.4.0",
    "packaging>=25.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "polars>=1.36.1",
    "tinycta>=0.8.4",
]
[project.optional-dependencies]
dev = [
    "pytest-cov>=7.0.0",
    "pytest-html>=4.1.1",
    "pytest==9.0.2",
    "pre-commit==4.5.1",
    "marimo==0.18.4",
    "pdoc>=16.0.0",
    "python-dotenv==1.2.1"
]

[project.urls]
Homepage = "https://tschm.github.io/cs"
