# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: echo "Checkout"


      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tschm/jupyter
          dockerfile: binder/Dockerfile
          target: builder
          tag_with_ref: true




#
## A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  # This workflow contains a single job called "build"
#  test:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: ./binder
#          file: Dockerfile
#          platforms: linux/amd64,linux/arm64,linux/386
#          push: true
#          tags: tschm/cs:latest
#
#
##    # Steps represent a sequence of tasks that will be executed as part of the job
##    steps:
##      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
##      - uses: actions/checkout@v2
##      # Runs a single command using the runners shell
##      #- name: test
##      - run: make build
##
##      - uses: docker/build-push-action@v2
##        with:
##          username: ${{ secrets.DOCKER_USERNAME }}
##          password: ${{ secrets.DOCKER_PASSWORD }}
##          context: .
##          dockerfile: ./binder/Dockerfile
##          #repository: tschm/cs
##          #tag_with_ref: true
##          push: true
##
##          #with:
##          #  context: .
##          #  file: ./Dockerfile
